### ISSUE TITLE
Plugin un-setting colorcolumn setting

### ISSUE THREAD

**Issue by Am3ra** [Bekaboo/deadcolumn.nvim#3] opened 2023-03-27 00:34 UTC
I have the setting `vim.o.colorcolumn = '100'`, which normally works and sets the value. 

When running the plugin with `lazy.nvim`, and then running `:set colorcolumn?` to verify the value, the setting appears empty. Setting the value to 100 in the buffer makes the plugin work normally afterwards.

Uninstalling and then verifying the value of the setting, the setting has the correct value.

**Comment by Bekaboo** [comment] 2023-03-27 00:48
This is expected if you are using the default config. What is your config and what do you think is the expected behavior?

**Comment by niveK77pur** [comment] 2023-03-27 08:17
I observe the same behaviour when settting the colorcolumn via the modeline using `vim: cc=60`. Removing the plugin makes the colorcolumn be set accordingly as well for me. I am using the default config by setting `config = true` with lazy.nvim.

The behaviour I expected is that `cc` would be set accordingly, and that this plugin would pick up on it. This would allow to have file specific column widths. Having to set it explicitly and manually despite it being expressed already as a modeline or a vimrc setting (as OP mentioned) feels counter-intuitive.

**Comment by Bekaboo** [comment] 2023-03-27 16:57
> I observe the same behaviour when settting the colorcolumn via the modeline using vim: cc=60

Thanks for reporting, I can reproduce the bug where the settings from modelines are ignored. It should now be fixed in the `dev` branch, please check it out and tell me if it is still an issue.

> The behaviour I expected is that cc would be set accordingly

I want to clarify here that the output of `:echo &cc` or `:lua =vim.wo.cc` is expected to be empty if you are using default config, which only shows `colorcolumn` when you are in insert or replacing mode, so you should expect `cc` to be empty when you are in normal mode, else the `colorcolumn` will be shown. To make `colorcolumn` visible in both insert and normal mode, change the `modes` option, you can find all available options and their default values [here](https://github.com/Bekaboo/deadcolumn.nvim#options).

**Comment by Am3ra** [comment] 2023-03-27 23:12
@Bekaboo I guess what I expected the behaviour to be is to be able to set the colorcolumn setting in the config, and for the plugin to work normally. Currently, the color column doesnt show up until I manually set the colorcolumn in the buffer.

**Comment by Bekaboo** [comment] 2023-03-27 23:20
@Am3ra I don't get your point. Do you mean you want colorcolumn to be shown in normal mode? If so, change the `modes` option in your config.

**Comment by niveK77pur** [comment] 2023-03-28 12:39
> It should now be fixed in the dev branch, please check it out and tell me if it is still an issue.

Works great now thank you!

I might need another small clarification: I suppose it is normal that `:set cc?` returns nothing/empty, even after the value was set? I figure the plugin takes over here so it can do its magic.

> I want to clarify here

And my bad, I wasn't very precise there. I was referring to the broken `cc` modeline option, not implying that the plugin should set a value for it! I think that would be a little confusing.

On second thought though, the plugin could set `cc="+1"`  or `cc="+0"` if the option was left empty. I feel like that would be quite non-intrusive and would trigger the `colorcolumn` to become visible if `textwidth` was already set. Just a random idea though, feel free to ignore.

**Comment by Bekaboo** [comment] 2023-03-28 14:55
@niveK77pur Glad to hear that it has been fixed, I have merged that to master branch.

> On second thought though, the plugin could set cc="+1" or cc="+0" if the option was left empty. I feel like that would be quite non-intrusive and would trigger the colorcolumn to become visible if textwidth was already set. Just a random idea though, feel free to ignore.

That could be confusing for a user that does not set cc for some filetypes but has `tt` set. It is a good idea, though, I think I would put it in the FAQ section.

**Comment by Bekaboo** [comment] 2023-03-31 01:46
I'm closing this issue because Am3ra is not responding. @Am3ra If you still have any question, feel free to contact me.

**Closed by Bekaboo** 2023-03-31 01:46 UTC

**Comment by Bekaboo** [comment] 2023-03-31 05:53
> On second thought though, the plugin could set cc="+1" or cc="+0" if the option was left empty. I feel like that would be quite non-intrusive and would trigger the colorcolumn to become visible if textwidth was already set. Just a random idea though, feel free to ignore.

@niveK77pur A new option `opts.extra.follow_tw` has landed on `dev` branch, please check it out if you are interested in it.

**Comment by niveK77pur** [comment] 2023-03-31 10:32
Thank you! The `follow_tw` seems to work great! There's only a minor "issue" that I observe. What to do when BOTH `cc` and `tw` were set? As of right now, it seems that `tw` takes precedence. I think it would be cool to have another setting to control what happens in that case. Either of the following seem reasonable to me (not sure which of the 3 should become the default behaviour)

- Precedence for `tw` (i.e. ignore `cc`)
- Precedence for `cc` (i.e. ignore `tw`)
- Merge values of `cc` and `tw` (i.e. `cc=10 tw=5` would become `cc=10,5`)

**Comment by Bekaboo** [comment] 2023-03-31 14:42
Option 2 seems more natural to me. There is a fix on `dev` now that makes this plugin to respect `cc` set from modeline even when `tw` is set and `follow_tw` is set to true, please check if works for you. However, I will not provide options for user to choose between the three options here as it will make the code unnecessarily complicated.

**Comment by niveK77pur** [comment] 2023-04-02 13:09
I have tried and observed the following.

- both `cc` and `tw` are set from the modeline: `tw` gets prioritized and `cc` gets ignored
- `cc` is set in ftplugin and `tw` is set from modeline: `tw` gets prioritized and `cc` gets ignored
-  `cc` is set from modeline and `tw` is set in ftplugin: `tw` gets prioritized and `cc` gets ignored
- both `cc` and `tw` are set from ftplugin: `cc` gets prioritized and `tw` gets ignored.

I hope it is not a problem somewhere in my configuration, but `tw` still gets precedence in all but the last case where both were set from the ftplugin.

**Comment by Bekaboo** [comment] 2023-04-02 14:28
@niveK77pur Hi, thanks for your feedback!

However I cannot reproduce the bugs. In my case:

- both `cc` and `tw` are set from the modeline: `cc` gets prioritized
- `cc` is set in ftplugin and `tw` is set from modeline: `cc` gets prioritized
- `cc` is set from modeline and `tw` is set in ftplugin: `cc` gets prioritized
- both `cc` and `tw` are set from ftplugin: `cc` gets prioritized

Did you **lazy-load** the plugin? This can be an issue because deadcolumn depends on some autocmds that triggered on reading the file to determine if `cc` or `tw` is set from ftplugins and modelines.

**Comment by Bekaboo** [comment] 2023-04-03 21:06
@niveK77pur Cannot reproduce.

And I realized that this issue has become too long and off-topic. For problems about `follow_cc`, please open another issue and we can discuss there. I also uploaded a template for bug report, hope that will help us addressing this issue.
